/** Catalog of every implemented rule (id → human explanation). Mirrors the detectors 1:1. */
export const RULES: Record<string, { summary: string; fix: string }> = {
  "VC-SECRET-PRIVATE-KEY": { summary: "A PEM private key is committed in source.", fix: "Remove it, rotate the key, load keys from a secret manager." },
  "VC-SECRET-AWS-KEY": { summary: "An AWS access key id (AKIA…) is committed.", fix: "Rotate the key; use IAM roles / env vars." },
  "VC-SECRET-GITHUB": { summary: "A GitHub token (ghp_/github_pat_) is committed.", fix: "Revoke it in GitHub settings; store in CI secrets." },
  "VC-SECRET-OPENAI": { summary: "An OpenAI-style secret key (sk-…) is committed.", fix: "Rotate the key; read from process.env at runtime." },
  "VC-SECRET-STRIPE": { summary: "A Stripe live secret key (sk_live/rk_live) is committed.", fix: "Roll the key in Stripe; never ship it client-side." },
  "VC-SECRET-GOOGLE": { summary: "A Google API key (AIza…) is committed.", fix: "Restrict and rotate the key in Google Cloud." },
  "VC-SECRET-SLACK": { summary: "A Slack token (xox…) is committed.", fix: "Revoke the token; store it in secrets." },
  "VC-SECRET-HIGH-ENTROPY": { summary: "A high-entropy value is hardcoded to a secret-named variable.", fix: "Move it to an env var / secret manager." },
  "VC-ENV-COMMITTED": { summary: "A .env file is not gitignored, so its secrets are likely committed.", fix: "Gitignore .env, purge it from history, rotate secrets." },
  "VC-ENV-DRIFT": { summary: "Variables exist in .env but are not documented in .env.example.", fix: "List every var (keys only) in .env.example." },
  "VC-ENV-MISSING": { summary: "Variables documented in .env.example are missing from .env.", fix: "Set the missing variables before deploy." },
  "VC-RCE-EVAL": { summary: "eval()/new Function() runs a non-literal value (RCE).", fix: "Never eval dynamic input; use JSON.parse or a dispatch table." },
  "VC-RCE-CHILD-PROCESS": { summary: "child_process runs a non-literal command (command injection).", fix: "Use execFile with a fixed program + args array; validate input." },
  "VC-SQLI-TEMPLATE": { summary: "SQL is built via template interpolation (SQL injection).", fix: "Use parameterized queries ($1, ?)." },
  "VC-SQLI-CONCAT": { summary: "SQL is built via string concatenation (SQL injection).", fix: "Use parameterized queries instead of concatenation." },
  "VC-CORS-WILDCARD": { summary: "CORS allows any origin ('*'), dangerous with credentials.", fix: "Restrict origin to an explicit allowlist." },
  "VC-JWT-NONE": { summary: "JWT 'none' algorithm is permitted (signature bypass).", fix: "Pin a strong algorithm and reject 'none'." },
  "VC-JWT-UNPINNED": { summary: "jwt.verify() does not pin algorithms (algorithm confusion).", fix: "Pass { algorithms: ['HS256'] }." },
  "VC-COOKIE-INSECURE": { summary: "An auth/session cookie is set without httpOnly + secure.", fix: "Set { httpOnly: true, secure: true, sameSite: 'lax' }." },
  "VC-ROUTE-NO-AUTH": { summary: "A route handler has no visible auth/authorization check (review).", fix: "Confirm it is public, or add an auth middleware / session check." },
  "VC-INPUT-NO-VALIDATION": { summary: "Request input is read without a schema validator imported.", fix: "Validate req body/query/params with zod/joi/yup/valibot." },
  "VC-NEXT-PUBLIC-SECRET": { summary: "A NEXT_PUBLIC_* var holds a secret and is bundled into client JS.", fix: "Drop the NEXT_PUBLIC_ prefix; read it only on the server." },
  "VC-SUPABASE-SERVICE-ROLE": { summary: "The Supabase service_role key (bypasses RLS) is referenced.", fix: "Use the anon key client-side; keep service_role server-only." },
  "VC-STACK-EXPOSURE": { summary: "An error stack trace is returned in the HTTP response.", fix: "Log stacks server-side; return a generic message." },
};
